import React from 'react';
import { Button } from '@/components/ui/button';

const HelpPage: React.FC = () => {
  const faqs = [
    {
      question: "How do I create a story?",
      answer: "To create a story, sign in to your account and click the 'Create' button in the navigation bar. Follow the step-by-step wizard to customize your story with characters, settings, and plot elements."
    },
    {
      question: "Can I personalize stories with my child's name?",
      answer: "Yes! Our personalization feature allows you to include your child's name, age, and interests in the story. This makes the reading experience more engaging and meaningful for your child."
    },
    {
      question: "How do I change my subscription plan?",
      answer: "You can change your subscription plan at any time by going to your Account Settings and selecting 'Billing'. From there, you can upgrade or downgrade your plan."
    },
    {
      question: "Are the stories safe for children?",
      answer: "Absolutely. All content generated by our AI is carefully filtered and reviewed to ensure it's appropriate for children. We maintain strict guidelines to prevent any harmful or inappropriate content."
    },
    {
      question: "Can I download stories to read offline?",
      answer: "Yes, subscribers can export stories in PDF format for offline reading. This feature is available in your Account Settings under 'Export Options'."
    },
    {
      question: "How do I contact customer support?",
      answer: "You can reach our support team by visiting the Contact page or emailing support@taleforge.com. We typically respond within 24 hours."
    }
  ];

  const quickLinks = [
    { title: "Getting Started", description: "Learn the basics of Tale Forge", anchor: "#getting-started" },
    { title: "Story Creation", description: "Tips for creating great stories", anchor: "#story-creation" },
    { title: "Account Management", description: "Subscription and billing help", anchor: "#account-management" }
  ];

  return (
    <div className="page-container">
      {/* Hero Section */}
      <section className="p-section text-center">
        <div className="container-lg">
          <div className="glass-card">
            <h1 className="title-hero mb-8">
              Help Center
            </h1>
            <p className="text-body text-xl max-w-4xl mx-auto mb-12 text-slate-200">
              Find answers to common questions and learn how to make the most of Tale Forge
            </p>
            
            {/* Quick Links Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {quickLinks.map((link, index) => (
                <a 
                  key={index}
                  href={link.anchor} 
                  className="glass-card hover:border-amber-400/40 transition-all duration-300"
                >
                  <h3 className="title-card mb-3">{link.title}</h3>
                  <p className="text-body text-slate-300">{link.description}</p>
                </a>
              ))}
            </div>
          </div>
        </div>
      </section>
      {/* FAQ Section */}
      <section className="p-section">
        <div className="container-lg">
          <div className="glass-card">
            <h2 className="title-section text-center mb-12">
              Frequently Asked Questions
            </h2>
            
            <div className="space-y-6 mb-12">
              {faqs.map((faq, index) => (
                <div key={index} className="glass-card">
                  <h3 className="title-card mb-3">
                    {faq.question}
                  </h3>
                  <p className="text-body text-slate-300">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>

            {/* Contact Support Section */}
            <div className="text-center">
              <h3 className="title-section mb-6">
                Still Need Help?
              </h3>
              <p className="text-body mb-8 text-slate-200 max-w-2xl mx-auto">
                Our support team is here to assist you with any questions or issues you may have.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button 
                  asChild
                  variant="default"
                  size="lg"
                >
                  <a href="/contact">Contact Support</a>
                </Button>
                <Button 
                  asChild
                  variant="secondary"
                  size="lg"
                >
                  <a href="mailto:support@taleforge.com">Email Support</a>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default HelpPage;