import React from 'react';
import Text from '@/components/atoms/Text';

const HelpPage: React.FC = () => {
  const faqs = [
    {
      question: "How do I create a story?",
      answer: "To create a story, sign in to your account and click the 'Create' button in the navigation bar. Follow the step-by-step wizard to customize your story with characters, settings, and plot elements."
    },
    {
      question: "Can I personalize stories with my child's name?",
      answer: "Yes! Our personalization feature allows you to include your child's name, age, and interests in the story. This makes the reading experience more engaging and meaningful for your child."
    },
    {
      question: "How do I change my subscription plan?",
      answer: "You can change your subscription plan at any time by going to your Account Settings and selecting 'Billing'. From there, you can upgrade or downgrade your plan."
    },
    {
      question: "Are the stories safe for children?",
      answer: "Absolutely. All content generated by our AI is carefully filtered and reviewed to ensure it's appropriate for children. We maintain strict guidelines to prevent any harmful or inappropriate content."
    },
    {
      question: "Can I download stories to read offline?",
      answer: "Yes, subscribers can export stories in PDF format for offline reading. This feature is available in your Account Settings under 'Export Options'."
    },
    {
      question: "How do I contact customer support?",
      answer: "You can reach our support team by visiting the Contact page or emailing support@taleforge.com. We typically respond within 24 hours."
    }
  ];

  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <Text variant="h1" weight="bold" className="text-3xl mb-8">
        Help Center
      </Text>
      
      <div className="bg-indigo-50 rounded-lg p-6 mb-12">
        <Text variant="h2" weight="semibold" className="text-xl mb-4">
          Quick Links
        </Text>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <a href="#getting-started" className="bg-white p-4 rounded shadow hover:shadow-md transition-shadow">
            <Text variant="h3" weight="semibold" className="mb-2">
              Getting Started
            </Text>
            <Text variant="p" size="sm" color="secondary">
              Learn the basics of Tale Forge
            </Text>
          </a>
          <a href="#story-creation" className="bg-white p-4 rounded shadow hover:shadow-md transition-shadow">
            <Text variant="h3" weight="semibold" className="mb-2">
              Story Creation
            </Text>
            <Text variant="p" size="sm" color="secondary">
              Tips for creating great stories
            </Text>
          </a>
          <a href="#account-management" className="bg-white p-4 rounded shadow hover:shadow-md transition-shadow">
            <Text variant="h3" weight="semibold" className="mb-2">
              Account Management
            </Text>
            <Text variant="p" size="sm" color="secondary">
              Subscription and billing help
            </Text>
          </a>
        </div>
      </div>
      
      <div className="mb-12">
        <Text variant="h2" weight="bold" className="text-2xl mb-6">
          Frequently Asked Questions
        </Text>
        
        <div className="space-y-6">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-white p-6 rounded-lg shadow">
              <Text variant="h3" weight="semibold" className="text-lg mb-2">
                {faq.question}
              </Text>
              <Text variant="p" color="secondary">
                {faq.answer}
              </Text>
            </div>
          ))}
        </div>
      </div>
      
      <div className="bg-white p-8 rounded-lg shadow">
        <Text variant="h2" weight="bold" className="text-2xl mb-4">
          Still Need Help?
        </Text>
        <Text variant="p" className="mb-6">
          Our support team is here to assist you with any questions or issues you may have.
        </Text>
        <div className="flex flex-col sm:flex-row gap-4">
          <a 
            href="/contact" 
            className="bg-indigo-600 text-white px-6 py-3 rounded-md font-medium hover:bg-indigo-700 transition-colors text-center"
          >
            Contact Support
          </a>
          <a 
            href="mailto:support@taleforge.com" 
            className="border border-indigo-600 text-indigo-600 px-6 py-3 rounded-md font-medium hover:bg-indigo-50 transition-colors text-center"
          >
            Email Support
          </a>
        </div>
      </div>
    </div>
  );
};

export default HelpPage;