import React from 'react';

const HelpPage: React.FC = () => {
  const faqs = [
    {
      question: "How do I create a story?",
      answer: "To create a story, sign in to your account and click the 'Create' button in the navigation bar. Follow the step-by-step wizard to customize your story with characters, settings, and plot elements."
    },
    {
      question: "Can I personalize stories with my child's name?",
      answer: "Yes! Our personalization feature allows you to include your child's name, age, and interests in the story. This makes the reading experience more engaging and meaningful for your child."
    },
    {
      question: "How do I change my subscription plan?",
      answer: "You can change your subscription plan at any time by going to your Account Settings and selecting 'Billing'. From there, you can upgrade or downgrade your plan."
    },
    {
      question: "Are the stories safe for children?",
      answer: "Absolutely. All content generated by our AI is carefully filtered and reviewed to ensure it's appropriate for children. We maintain strict guidelines to prevent any harmful or inappropriate content."
    },
    {
      question: "Can I download stories to read offline?",
      answer: "Yes, subscribers can export stories in PDF format for offline reading. This feature is available in your Account Settings under 'Export Options'."
    },
    {
      question: "How do I contact customer support?",
      answer: "You can reach our support team by visiting the Contact page or emailing support@taleforge.com. We typically respond within 24 hours."
    }
  ];

  const quickLinks = [
    { title: "Getting Started", description: "Learn the basics of Tale Forge", anchor: "#getting-started" },
    { title: "Story Creation", description: "Tips for creating great stories", anchor: "#story-creation" },
    { title: "Account Management", description: "Subscription and billing help", anchor: "#account-management" }
  ];

  return (
    <div className="min-h-screen flex flex-col relative overflow-hidden">
      {/* Refined Floating Elements - Same as HomePage */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-2 h-2 bg-amber-400/20 rounded-full animate-pulse"></div>
        <div className="absolute top-3/4 right-1/3 w-1 h-1 bg-amber-500/25 rounded-full animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-3/4 w-1.5 h-1.5 bg-amber-300/15 rounded-full animate-pulse delay-2000"></div>
        <div className="absolute top-1/3 right-2/3 w-1 h-1 bg-amber-600/20 rounded-full animate-pulse delay-3000"></div>
      </div>

      {/* Hero Section */}
      <div className="relative z-10 flex-1 flex items-center justify-center px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center max-w-4xl mx-auto">
          {/* Refined Hero Container - Same as HomePage */}
          <div className="refined-card bg-slate-900/20 border border-amber-400/10 rounded-2xl p-8 md:p-12 lg:p-16">
            {/* Header */}
            <h1 className="fantasy-heading-cinzel text-4xl sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl font-bold mb-6 sm:mb-8 text-center">
              Help Center
            </h1>
            <p className="text-lg sm:text-xl md:text-2xl text-slate-300 max-w-4xl mx-auto leading-relaxed mb-12 sm:mb-16 text-center">
              Find answers to common questions and learn how to make the most of Tale Forge
            </p>
            
            {/* Quick Links Grid - Same structure as HomePage features */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
              {quickLinks.map((link, index) => (
                <a 
                  key={index}
                  href={link.anchor} 
                  className="glass-card backdrop-blur-md bg-white/5 border border-white/10 rounded-lg p-6"
                >
                  <h3 className="text-xl font-semibold text-white mb-2">{link.title}</h3>
                  <p className="text-white/80">{link.description}</p>
                </a>
              ))}
            </div>
          </div>
        </div>
      </div>
        
      {/* FAQ Section - Same structure as HomePage Featured Stories */}
      <div className="relative z-10 px-4 sm:px-6 lg:px-8 py-16">
        <div className="max-w-4xl mx-auto">
          <div className="glass-enhanced backdrop-blur-lg bg-black/20 border border-white/20 rounded-2xl p-8 md:p-12">
            <h2 className="fantasy-heading-cinzel text-3xl md:text-4xl font-bold text-center mb-12">
              Frequently Asked Questions
            </h2>
            
            <div className="space-y-6">
              {faqs.map((faq, index) => (
                <div key={index} className="glass-card bg-white/5 border border-white/10 rounded-lg p-6">
                  <h3 className="text-xl font-semibold text-white mb-2">
                    {faq.question}
                  </h3>
                  <p className="text-white/80">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>

            {/* Contact Support Section */}
            <div className="text-center mt-12">
              <h3 className="text-2xl font-bold text-white mb-4">
                Still Need Help?
              </h3>
              <p className="text-white/80 mb-8 leading-relaxed">
                Our support team is here to assist you with any questions or issues you may have.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <a 
                  href="/contact" 
                  className="fantasy-cta px-8 py-4 text-lg rounded-xl shadow-2xl transform hover:scale-105 transition-all duration-300"
                >
                  Contact Support
                </a>
                <a 
                  href="mailto:support@taleforge.com" 
                  className="glass-card text-white border-2 border-amber-400/50 hover:border-amber-400 font-semibold px-8 py-4 text-lg rounded-xl backdrop-blur-md hover:bg-amber-400/10 transition-all duration-300 text-center"
                >
                  Email Support
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HelpPage;