import React, { useState, useEffect } from 'react';
import { useParams, useLocation, useNavigate, Link } from 'react-router-dom';
import { useStory } from '@/utils/performance.tsx';
import Button from '@/components/atoms/Button';
import Text from '@/components/atoms/Text';
import StoryImage from '@/components/atoms/StoryImage';
import { supabase } from '@/lib/supabase';

interface StoryStats {
  totalWords: number;
  totalSegments: number;
  readingTime: string;
  completionTime: string;
}

const StoryCompletePage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const location = useLocation();
  const navigate = useNavigate();
  const [showConfetti, setShowConfetti] = useState(true);
  const [isSharing, setIsSharing] = useState(false);
  const [showShareSuccess, setShowShareSuccess] = useState(false);
  const [isGeneratingAudio, setIsGeneratingAudio] = useState(false);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [stats, setStats] = useState<StoryStats | null>(null);

  // Get story data
  const { data: story, isLoading, error } = useStory(id || null);

  // Calculate story stats
  useEffect(() => {
    if (!story || !story.segments) return;
    
    const totalWords = story.segments.reduce((sum, segment) => 
      sum + (segment.content?.split(' ').length || 0), 0
    );
    
    const readingTime = Math.max(1, Math.ceil(totalWords / 150)); // Assuming 150 WPM for children
    
    setStats({
      totalWords,
      totalSegments: story.segments.length,
      readingTime: `${readingTime} minute${readingTime > 1 ? 's' : ''}`,
      completionTime: new Date().toLocaleDateString()
    });
  }, [story]);

  // Hide confetti after animation
  useEffect(() => {
    const timer = setTimeout(() => setShowConfetti(false), 5000);
    return () => clearTimeout(timer);
  }, []);

  const handleShareToLibrary = async () => {
    if (!story) return;
    
    setIsSharing(true);
    try {
      const { error } = await supabase
        .from('stories')
        .update({ 
          is_public: true, 
          is_completed: true,
          completed_at: new Date().toISOString(),
          public_shared_at: new Date().toISOString(),
          // Ensure story has proper metadata for discovery
          status: 'published'
        })
        .eq('id', story.id);
      
      if (error) throw error;
      
      // Show celebration modal instead of alert
      setShowShareSuccess(true);
    } catch (error) {
      console.error('Error sharing story:', error);
      alert('Failed to share story. Please try again.');
    } finally {
      setIsSharing(false);
    }
  };

  const handleDownloadStory = () => {
    if (!story) return;
    
    // Create story text
    const storyText = `${story.title}\n\n${story.segments.map((segment, index) => 
      `Chapter ${index + 1}\n${segment.content}`
    ).join('\n\n')}\n\nThe End\n\nGenerated by Tale Forge - https://tale-forge.com`;
    
    // Create download
    const blob = new Blob([storyText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${story.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleGenerateAudio = async () => {
    if (!story) return;
    
    setIsGeneratingAudio(true);
    try {
      // Placeholder for TTS generation
      // In real implementation, this would call a TTS service
      setTimeout(() => {
        setAudioUrl('/placeholder-audio.mp3');
        setIsGeneratingAudio(false);
      }, 3000);
    } catch (error) {
      console.error('Error generating audio:', error);
      setIsGeneratingAudio(false);
    }
  };

  const handleSocialShare = () => {
    if (!story) return;
    
    const shareText = `I just created an amazing story called "${story.title}" on Tale Forge! 📚✨`;
    const shareUrl = `https://tale-forge.com/stories/${story.id}`;
    
    if (navigator.share) {
      navigator.share({
        title: story.title,
        text: shareText,
        url: shareUrl
      });
    } else {
      // Fallback to clipboard
      navigator.clipboard.writeText(`${shareText} ${shareUrl}`);
      alert('Story link copied to clipboard!');
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-amber-400"></div>
      </div>
    );
  }

  if (error || !story) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="glass-enhanced p-8 rounded-2xl text-center max-w-md">
          <span className="text-6xl mb-4 block">😞</span>
          <h2 className="text-xl font-bold text-white mb-2">Story not found</h2>
          <Link to="/stories" className="fantasy-cta px-4 py-2 rounded-lg">
            Back to Stories
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen py-6 relative">
      {/* Confetti Effect */}
      {showConfetti && (
        <div className="fixed inset-0 pointer-events-none z-50">
          {Array.from({ length: 50 }).map((_, i) => (
            <div
              key={i}
              className="absolute animate-bounce"
              style={{
                left: `${Math.random() * 100}%`,
                animationDelay: `${Math.random() * 2}s`,
                animationDuration: `${2 + Math.random() * 3}s`
              }}
            >
              {['🎉', '✨', '🌟', '📚', '🎈'][Math.floor(Math.random() * 5)]}
            </div>
          ))}
        </div>
      )}

      <div className="max-w-4xl mx-auto px-4">
        {/* Hero Section */}
        <div className="glass-enhanced p-8 md:p-12 rounded-2xl text-center mb-8">
          <div className="text-8xl mb-6 animate-pulse">🏆</div>
          <h1 className="fantasy-heading-cinzel text-4xl md:text-6xl lg:text-7xl mb-4">
            Story Complete!
          </h1>
          <h2 className="fantasy-heading text-2xl md:text-3xl mb-6 text-amber-300">
            "{story.title}"
          </h2>
          <p className="text-white/80 text-xl mb-8 max-w-2xl mx-auto">
            🎉 Congratulations! You've created an incredible {story.genre} adventure. 
            Your creativity and choices brought this magical story to life!
          </p>
          
          {stats && (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-2xl mx-auto">
              <div className="glass-card p-4 rounded-lg">
                <div className="text-2xl font-bold text-amber-400">{stats.totalSegments}</div>
                <div className="text-white/60 text-sm">Chapters</div>
              </div>
              <div className="glass-card p-4 rounded-lg">
                <div className="text-2xl font-bold text-amber-400">{stats.totalWords}</div>
                <div className="text-white/60 text-sm">Words</div>
              </div>
              <div className="glass-card p-4 rounded-lg">
                <div className="text-2xl font-bold text-amber-400">{stats.readingTime}</div>
                <div className="text-white/60 text-sm">Reading Time</div>
              </div>
              <div className="glass-card p-4 rounded-lg">
                <div className="text-2xl font-bold text-amber-400">Today</div>
                <div className="text-white/60 text-sm">Completed</div>
              </div>
            </div>
          )}
        </div>

        {/* Action Cards Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
          
          {/* Share to Library */}
          <div className="glass-card p-6 rounded-2xl">
            <div className="text-4xl mb-4">🌟</div>
            <h3 className="fantasy-heading text-xl mb-3">Share Your Story</h3>
            <p className="text-white/70 text-sm mb-4">
              Share your amazing story with the Tale Forge community in our public library.
            </p>
            <Button
              onClick={handleShareToLibrary}
              disabled={isSharing}
              className="w-full fantasy-cta"
            >
              {isSharing ? 'Sharing...' : '✨ Share to Library'}
            </Button>
          </div>

          {/* Download Story */}
          <div className="glass-card p-6 rounded-2xl">
            <div className="text-4xl mb-4">📥</div>
            <h3 className="fantasy-heading text-xl mb-3">Download Story</h3>
            <p className="text-white/70 text-sm mb-4">
              Download your complete story as a text file to keep forever.
            </p>
            <Button
              onClick={handleDownloadStory}
              variant="secondary"
              className="w-full"
            >
              📄 Download Text
            </Button>
          </div>

          {/* Generate Audio */}
          <div className="glass-card p-6 rounded-2xl">
            <div className="text-4xl mb-4">🎵</div>
            <h3 className="fantasy-heading text-xl mb-3">Audio Narration</h3>
            <p className="text-white/70 text-sm mb-4">
              Generate AI narration of your story for a magical listening experience.
            </p>
            <Button
              onClick={handleGenerateAudio}
              disabled={isGeneratingAudio}
              variant="magical"
              className="w-full"
            >
              {isGeneratingAudio ? 'Generating...' : '🎙️ Create Audio'}
            </Button>
            {audioUrl && (
              <audio controls className="w-full mt-3">
                <source src={audioUrl} type="audio/mpeg" />
              </audio>
            )}
          </div>

          {/* Social Share */}
          <div className="glass-card p-6 rounded-2xl">
            <div className="text-4xl mb-4">📱</div>
            <h3 className="fantasy-heading text-xl mb-3">Social Share</h3>
            <p className="text-white/70 text-sm mb-4">
              Share your creative achievement with friends and family.
            </p>
            <Button
              onClick={handleSocialShare}
              variant="outline"
              className="w-full"
            >
              🔗 Share Link
            </Button>
          </div>

          {/* Create Another */}
          <div className="glass-card p-6 rounded-2xl">
            <div className="text-4xl mb-4">✍️</div>
            <h3 className="fantasy-heading text-xl mb-3">Create Another</h3>
            <p className="text-white/70 text-sm mb-4">
              Ready for your next adventure? Create another magical story.
            </p>
            <Link to="/create">
              <Button variant="secondary" className="w-full">
                🎨 New Story
              </Button>
            </Link>
          </div>

          {/* View Library */}
          <div className="glass-card p-6 rounded-2xl">
            <div className="text-4xl mb-4">📚</div>
            <h3 className="fantasy-heading text-xl mb-3">Your Library</h3>
            <p className="text-white/70 text-sm mb-4">
              View all your created stories and discover new adventures.
            </p>
            <Link to="/stories">
              <Button variant="outline" className="w-full">
                📖 View Stories
              </Button>
            </Link>
          </div>
        </div>

        {/* Story Preview */}
        <div className="glass-card p-6 rounded-2xl">
          <h3 className="fantasy-heading text-2xl mb-6 text-center">Your Complete Story</h3>
          <div className="max-h-96 overflow-y-auto space-y-4">
            {story.segments.map((segment, index) => (
              <div key={segment.id} className="border-l-4 border-amber-400 pl-4">
                <div className="text-amber-300 font-semibold mb-2">Chapter {index + 1}</div>
                <div className="text-white/80 leading-relaxed">{segment.content}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Share Success Modal */}
        {showShareSuccess && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="glass-enhanced p-8 rounded-2xl max-w-md text-center">
              <div className="text-6xl mb-4">🌟</div>
              <h3 className="fantasy-heading text-2xl mb-4">Story Shared!</h3>
              <p className="text-white/80 mb-6">
                Your amazing story is now available in the public library for everyone to discover and enjoy!
              </p>
              <div className="space-y-3">
                <Link to="/discover" className="block">
                  <Button className="w-full fantasy-cta">
                    🔍 Browse Public Library
                  </Button>
                </Link>
                <Button 
                  onClick={() => setShowShareSuccess(false)}
                  variant="outline"
                  className="w-full"
                >
                  Continue Celebrating
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default StoryCompletePage;